### ISSUE TITLE
Cannot create new plural entries

### ISSUE THREAD

**Issue by msierks** [raulferras/PHP-po-parser#32]
It appears it is not possible to create a new plural entry using updateEntry. I need this ability for my use case.

**Comment by raulferras** [comment]
I'm planning to refactor `updateEntry` because it currently ignores a lot of entry properties. 
Meanwhile I could create a new method to mantain backwards compatibility.

**Comment by msierks** [comment]
Awesome, good to hear.

**Comment by msierks** [comment]
any ETA in this ?

**Comment by raulferras** [comment]
I cannot promise anything, but I would like to finish this next week if real life allows me :S

**Comment by raulferras** [comment]
I've created a new branch in preparation for new version 5.0. This new version includes a new method `setEntry` which in theory will allow to create/modify new entries and set every member.

**Comment by msierks** [comment]
I have noticed you merged in the "updateEntryPlural" function. I will use this till 5.0 is ready.

**Comment by raulferras** [comment]
Great!
