### ISSUE TITLE
Unable to parse po files with multiline translations

### ISSUE THREAD

**Issue by msierks** [raulferras/PHP-po-parser#35]
When parsing msgid's and msgstr's with multiple lines, the result is an empty string.

https://www.gnu.org/software/gettext/manual/html_node/PO-Files.html

**Comment by raulferras** [comment]
Could you provide the .po file you're having problems with?

**Comment by proctar** [comment]
Something like this won't work:

msgid "myid"
msgstr "line1"
     "line2"
     "line"

Online "line1" is retrieved, but the other lines are lost.

**Comment by raulferras** [comment]
Should be fixed in #68
