### ISSUE TITLE
Notice Error: Undefined index

### ISSUE THREAD

**Issue by gemal** [raulferras/PHP-po-parser#48]
I saw this:
Notice Error: Undefined index:  in [PHP-po-parser\Sepia\PoParser.php, line 304]

and I tracked it down to the following PO file entry:

```
msgid ""
msgstr ""
"Project-Id-Version: 1.0\n"
"POT-Creation-Date: \n"
"PO-Revision-Date: 2015-09-22 15:58+0300\n"
"Language-Team: Support <support@dinnerbooking.com>\n"
"Language: en\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"

#index.ctp:101
msgid "test"
msgstr "test"

```

**Comment by gemal** [comment]
it's due to the missing space:
`#index.ctp:101`
versus
`# index.ctp:101`

not sure what could be done here?
msgfmt doesn't report an error in the file

**Comment by dereuromark** [comment]
Any line starting with # should be treated as comma, no matter how many or what characters follow
My PO also broke due to
```
...
msgstr "Spenden"

### Contact Ad

msgid "Title"
...
```

With the above `Undefined index: in` etc

**Comment by raulferras** [comment]
Sorry for not answering before, I'm quite busy currently.
Will try to take a look this weekend.
