### ISSUE TITLE
How do I get the msgstr[0] type entries set?

### ISSUE THREAD

**Issue by Saeven** [raulferras/PHP-po-parser#51]
I've tried a plethora of things, can't file anything in the tests that generates the right output when compiled.

```
$new_parser->setEntry( $key,[
   'msgid' => $msgid,
   'msgid_plural' => $new_entries[$key]['msgid_plural'],
   .. what else?
]);
```

I'm trying to achieve this type of output:

```
msgid "test"
msgid_plural "There are %count% values in the house"
msgstr[0] ""
msgstr[1] ""
```

Nothing I pass populates the plural forms..

Thanks for your kind help!

**Comment by Saeven** [comment]
Alright, checked the source and generated input that works, but it is horribly counterintuitive.

```
$new_parser->setEntry( $key,[
   'msgid' => $msgid,
   'msgid_plural' => $new_entries[$key]['msgid_plural'],
   'msgstr[0]' => [ 0 => 'abc'],
   'msgstr[1]' => [ 0 => 'abc123'],
]);
```

A better usage pattern I think, could be:

```
$new_parser->setEntry( $key,[
   'msgid' => "I found 1 fatal error",
   'msgid_plural' => "I found %d fatal errors",
   'msgstr' => [ 
       0 => "There's 1 error here",
       1 =>  "Wow %d errors!"
]);
```

Would you be open to a PR on this?

**Comment by raulferras** [comment]
What version are you using? v4 or v5?

**Comment by Saeven** [comment]
Hey Raul, I'm on dev-master.

**Comment by raulferras** [comment]
Checking it is the correct behaviour.  
`msgstr` can contain both multiline content:

```
'msgstr' => [
'line 1',
'line 2'
];

But it can also contain translations for specific plural messages:

```
'msgstr[0]' => '1 line',
'msgstr[1]' => '%d lines'
