### ISSUE TITLE
Parsing plural forms

### ISSUE THREAD

**Issue by dsas** [raulferras/PHP-po-parser#56]
I can't see how to parse translations for plural forms, when taking wrapped strings into account Here's the output I get when I print_r after calling parseFile on the attached [test.po.tar.gz](https://github.com/raulferras/PHP-po-parser/files/132736/test.po.tar.gz)

```
Array
(
    [%1$d UK region selected ] => Array
        (
            [msgid] => Array
                (
                    [0] => %1$d UK region selected 
                )

            [msgid_plural] => Array
                (
                    [0] => 
                    [1] => %1$d UK regions 
                    [2] => selected
                )

            [msgstr] => Array
                (
                    [0] => %1$d HX ertvba fryrpgrq
                    [1] => 
                    [2] => %1$d HX ertvbas 
                    [3] => fryrpgrq
                )

        )

)
```

So msgstr contains the case for each plural form, the first (singular form) is in index 0 and the rest is the plural form. I can't programatically know this though.

The obvious work around is to not use string wrapping, though that is the default for the gnu gettext suite...

**Comment by dsas** [comment]
Sorry, this looks like a duplicate of #41, are there any plans to make a new release?

**Comment by raulferras** [comment]
It looks like a different issue to me.
I will definitely take a look, thank you for your report.
