### ISSUE TITLE
"Notice Error: Undefined index" when having excess lines

### ISSUE THREAD

**Issue by gemal** [raulferras/PHP-po-parser#59]
I'm getting:
`Notice Error: Undefined index:  in [sepia\po-parser\src\Sepia\PoParser.php, line 304]`

when you po file looks like this:

```
msgid ""
msgstr ""
"Project-Id-Version: 1.0\n"
"POT-Creation-Date: \n"
"PO-Revision-Date: 2015-09-22 15:58+0300\n"
"Language-Team: Support <support@dinnerbooking.com>\n"
"Language: en\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"

#: test
msgid "xxxx"
msgstr ""

"yyyy"
"zzzz"
```

which according to `msgfmt --check` is valid

**Comment by raulferras** [comment]
Great, this will improve Unit Testing.

**Comment by gemal** [comment]
I checked cakephp and that seems to support that extra empty line

**Comment by dereuromark** [comment]
I have the same issue:

    Notice (8): Undefined index:  [ROOT/vendor/sepia/po-parser/src/Sepia/PoParser.php, line 304]

I parsed a CakePHP PO file.

**Comment by raulferras** [comment]
One question, does those 
```
"yyyy"
"zzzz"
```
belong to the msgid`xxxx` string?

**Comment by raulferras** [comment]
I'm closing this as no feedback was provided.
Feel free to repoen if still able to reproduce this behaviour.
