### ISSUE TITLE
Writing plural

### ISSUE THREAD

**Issue by dereuromark** [raulferras/PHP-po-parser#61]
https://github.com/Ben-Ho/PHP-po-parser/commit/9e7d57015d2e95fbf3ab156ed53d88f4b4e29ff9
This looks lik a valid fix and should be added IMO

**Comment by raulferras** [comment]
I will take a look thanks

**Comment by raulferras** [comment]
In that example it is hardcoded that there are two plural forms, so I cannot copy it as it is.
We may need to parse the headers better and check how many plural forms exist for the language.
