### ISSUE TITLE
So confusing to use

### ISSUE THREAD

**Issue by neotropic2023** [raulferras/PHP-po-parser#62]
I do appreciate this, but it is difficult to use. It lacks instructions and demos. You have code in your main file that does not exists nor works.

$pofile->updateEntry( $msgid, $msgstr ); (?) But no function in any of your files?
$pofile->write('ca.po'); returns Fatal error: Call to undefined method Sepia\PoParser::write()
So basically we can use this to parse and translate a file, but not save it?

No examples of using plurals. I see a function, but no example use.
I see mulitine, but no example.

The parsing is great, I just have to find a different method of updating/changing the text.

**Comment by raulferras** [comment]
I will take a look, it's been a long time since the last update and I remember everything worked fine. Maybe examples are obsolete.

**Comment by raulferras** [comment]
Version 5.0 has been released. Many things changed, may be easier to user for you. Feel free to reopen if still in doubt.
