### ISSUE TITLE
Not correct update Entity in setEntry

### ISSUE THREAD

**Issue by gorets** [raulferras/PHP-po-parser#67]
if the Entity exists and you need an update
![poedit](https://user-images.githubusercontent.com/419682/35610399-2e5d3456-0672-11e8-913c-2c0fcfc6f0eb.png)

PoParser line 449
if ($msgid !== $entry['msgid']) {

$msgid - string
$entry['msgid'] - array

**Comment by raulferras** [comment]
I see, for some reason internal catalog has the msgid inside an array of one item and therefore condition does not match.
I guess I can do a "hack" for this corner case... But it would be better if you could provide with a minimal catalog.po file that can reproduce this and see if we can fix it before reaching this point.
