### ISSUE TITLE
unsafe splitting of UTF-8 strings

### ISSUE THREAD

**Issue by stereoit** [raulferras/PHP-po-parser#79]
Hi, today I've added czech translation which gets split after 80 bytes which is exactly in the middle of UTF-8 multibyte sequence, thus producing non-ascii file.

`Slučovací pole v této sekci budou fungovat pouze v případě, že v Hromadné korespondenci vyberet <b>typ příjemce - Firma</b>`

It is split as (notice <C3>" and rest is on new line "<AD>)

```
msgstr ""
"Slu<C4><8D>ovac<C3><AD> pole v t<C3><A9>to sekci budou fungovat pouze v p<C5><99><C3><AD>pad<C4><9B>, <C5><BE>e v Hromadn<C3>"
"<A9> korespondenci vyberet <b>typ p<C5><99><C3><AD>jemce - Firma</b>"
```

It would be nice if it either splitted safely, or we had an option to not split lines at all.

**Comment by raulferras** [comment]
I see.
We can start by disabling splitting lines meanwhile we sesrch for a
solution to splitting uyf8 characters
