### ISSUE TITLE
Call to undefined method Sepia\PoParser\Catalog\CatalogArray::setEntry() 

### ISSUE THREAD

**Issue by AruldassD** [raulferras/PHP-po-parser#82]
Hello , in your github i used setentry() method to update the records , but it is not available in your current github library . can u help me in this ?

**Comment by raulferras** [comment]
Hello, there is no such method. 
If you want to add a new entry to the Catalog use `addEntry`.  
If what you want to do is to edit an entry, use `getEntry` to get it and just modify it. This method returns a reference to the entry, so you can modify it an it will stay modified in the catalog.

**Comment by AruldassD** [comment]
How i will update this entry : $entry = new Entry('You must fill in %s.', 'Test!');

$catalog->setEntry($entry); can u please help me in this ??

**Comment by AruldassD** [comment]
i used this method but my .po file is not updating $catalog->getEntry('You must fill in %s.', 'Test!'); 

this is my whole php code 

<?php
require_once('vendor/autoload.php');
use Sepia\PoParser\SourceHandler\FileSystem;
use Sepia\PoParser\Parser;
use Sepia\PoParser\Catalog;
use Sepia\PoParser\Catalog\Entry;


$fileHandler = new Sepia\PoParser\SourceHandler\FileSystem('test.po');

$poParser = new Sepia\PoParser\Parser($fileHandler);
$catalog  = $poParser->parse();
$catalog->getEntry('You must fill in %s.', 'Test!');

?>

**Comment by AruldassD** [comment]
This is my github url : https://github.com/AruldassD/poedit , i tried with getentry method also but not working can u please check index.php file ??? and help me in this ...
