### ISSUE TITLE
Quote is adding on very big string 

### ISSUE THREAD

**Issue by AruldassD** [raulferras/PHP-po-parser#84]
Hello , i'm using your package for editing po files ,  i'm having some field example:'X' and i'm having very big another field example:'Y' , if i'm editing X field, Y field's messageId is automatically updating and adding some '/' and quotes between the big string .  how can i restrict this ???? can u please help me in this ?? 

Orginal File Before Edit :

![image](https://user-images.githubusercontent.com/16668619/37963954-81b8b576-31dd-11e8-989c-5d11ef7111c1.png)

After Edit :
![image](https://user-images.githubusercontent.com/16668619/37964004-a81adaaa-31dd-11e8-9ea8-2c1a31532937.png)

Please check this screenshot , automatically '/' and quote is adding while editing  and also line is breaking and creating a newline..

**Comment by raulferras** [comment]
Closing as duplicated of #83
