### ISSUE TITLE
Error on compiling obsolete plurals

### ISSUE THREAD

**Issue by Stefaminator** [raulferras/PHP-po-parser#89]
`msgid_plural` and `msg_str[]` are missing the obsolete prefix (`#~`)

This produces broken .po-files:

```
#~ msgid "Mutter"
msgid_plural "Mütter"
msgstr[0] "мать"
msgstr[1] "матери"
msgstr[2] "матери"
```

Please fix it by prepending the `TOKEN_OBSOLETE` when the entry is obsolete in `buildMsgIdPlural` and `buildMsgStr` methods in `PoCompiler.php`. 

It try it by myself now and try to send you an Pull request.

**Comment by raulferras** [comment]
Could you write a test for it? Then we could code a solution around it ;)

**Comment by Stefaminator** [comment]
Sorry but I am a little bit in hurry. It was quite easy to fix. Please see my pull request.

To reproduce it just open a po-file with obsolete plurals and compile it again. You will see that msgid_plural and msgstr doesn't care about the obsolete flag while msgid does.

**Comment by raulferras** [comment]
Thanks for the PR!
