### ISSUE TITLE
Parser doesn't remove slashes before quotes

### ISSUE THREAD

**Issue by ondrejcech** [raulferras/PHP-po-parser#95]
Hi,

I believe that when parsed, the slashes should not be part of the string because it's an escape character.

```
msgid "a\"b\"c"
msgstr "quotes in \"translation\""

$entry->getMsgId() // a"b"c
$entry->getMsgStr() // quotes in "translation"
```

But you specifically test for that behavior in `ReadPoTest::testBasic`. Is there any reason for that? Am I missing something?

**Comment by raulferras** [comment]
It's been a long time so I should check it again more in deep.
A quick check in the code suggests that the parser indeed is not unescaping `\`, but I don't remember the reason behind that. 
Let me check it more deeply

**Comment by ondrejcech** [comment]
Thanks for your response. Do you have any updates? I've checked Symfony implementation on PoFileLoader and they're removing the escape character (using `stripcslashes`) - https://github.com/symfony/symfony/blob/6d10f8891ecdf480e4dccacc394b29b9dc85528a/src/Symfony/Component/Translation/Loader/PoFileLoader.php#L127

The same behavior is used in poEdit desktop app.

I'll create pull request with proposed change but I'd like to know if there's any reason behind.

**Comment by raulferras** [comment]
Sorry @ondrejcech , I haven't had time for it. Will try this week but I'm currently quite busy.
If you are willing to open a PR I will check it for sure.

**Comment by raulferras** [comment]
@ondrejcech , could you provide me a .po example file that does not have quotes escaped together with explaining which what program was it created?
It would help immensely to check if current implementation is wrong.

Thanks.

**Comment by ondrejcech** [comment]
Sorry for the late reply. I've prepared PR https://github.com/raulferras/PHP-po-parser/pull/96 that will solve the issue. I've checked the proposed behaviour with xgettext tool and it produces the same output.
